import random

# Hand-audited wordlists - no profanity, no body parts, no slurs, no double meanings
COLORS = [
    "crimson",
    "cerulean",
    "slate",
    "amber",
    "coral",
    "indigo",
    "jade",
    "lavender",
    "magenta",
    "navy",
    "olive",
    "peach",
    "ruby",
    "sage",
    "teal",
    "violet",
    "bronze",
    "copper",
    "ivory",
    "onyx",
    "pearl",
    "scarlet",
    "silver",
    "golden",
    "azure",
    "cobalt",
    "emerald",
    "garnet",
    "hazel",
    "lemon",
    "lime",
    "maple",
    "mint",
    "mocha",
    "plum",
    "rose",
    "sand",
    "snow",
    "storm",
    "sunset",
    "tangerine",
    "topaz",
    "turquoise",
    "walnut",
    "wheat",
    "wine",
    "charcoal",
    "flint",
    "frost",
]

ANIMALS = [
    "marmot",
    "pangolin",
    "axolotl",
    "capybara",
    "quokka",
    "narwhal",
    "okapi",
    "fennec",
    "alpaca",
    "otter",
    "panda",
    "koala",
    "penguin",
    "hedgehog",
    "flamingo",
    "toucan",
    "parrot",
    "dolphin",
    "seahorse",
    "starfish",
    "octopus",
    "mantis",
    "firefly",
    "monarch",
    "falcon",
    "osprey",
    "heron",
    "pelican",
    "crane",
    "egret",
    "swift",
    "wren",
    "finch",
    "lark",
    "robin",
    "sparrow",
    "cardinal",
    "oriole",
    "tanager",
    "warbler",
    "bunting",
    "hawk",
    "eagle",
    "owl",
    "raven",
    "jay",
    "magpie",
    "dove",
    "fox",
    "wolf",
    "lynx",
    "moose",
    "elk",
    "deer",
    "bison",
    "orca",
    "whale",
    "seal",
    "walrus",
    "puffin",
    "badger",
    "beaver",
    "rabbit",
    "hare",
    "squirrel",
    "chipmunk",
    "raccoon",
    "lemur",
    "gecko",
    "iguana",
    "tortoise",
    "newt",
    "salamander",
    "frog",
    "treefrog",
    "chameleon",
    "cobra",
    "python",
    "viper",
    "condor",
    "albatross",
    "stork",
    "ibis",
    "kiwi",
    "platypus",
    "wombat",
    "possum",
    "armadillo",
    "sloth",
    "anteater",
    "tapir",
    "manatee",
    "dugong",
    "meerkat",
    "mongoose",
    "porcupine",
    "chinchilla",
    "hamster",
    "ferret",
    "emu",
    "ostrich",
    "peacock",
    "pheasant",
    "grouse",
    "quail",
    "coyote",
    "jackal",
    "cheetah",
    "leopard",
    "panther",
    "jaguar",
    "cougar",
    "bobcat",
    "ocelot",
    "serval",
    "caracal",
    "margay",
    "gazelle",
    "impala",
    "oryx",
    "ibex",
    "chamois",
    "markhor",
    "tahr",
    "serow",
    "goral",
    "pika",
    "vole",
    "shrew",
    "mole",
    "dormouse",
    "jerboa",
    "gerbil",
    "degu",
    "cavia",
    "agouti",
    "paca",
    "hutia",
    "coypu",
    "muskrat",
    "lemming",
    "cricket",
    "mantid",
    "beetle",
]

# Words that should never appear in generated names (extra safety)
BANNED_WORDS: set[str] = set()


def generate_display_name() -> str:
    """Generate a random display name like 'crimson-marmot'."""
    for _ in range(100):
        color = random.choice(COLORS)
        animal = random.choice(ANIMALS)
        name = f"{color}-{animal}"
        if name not in BANNED_WORDS:
            return name
    # Fallback: pick first non-banned combination
    return f"{COLORS[0]}-{ANIMALS[0]}"


def is_valid_name(name: str) -> bool:
    """Check if a name follows our format and isn't banned."""
    if not name or len(name) > 50:
        return False
    parts = name.split("-")
    if len(parts) != 2:
        return False
    return parts[0] in COLORS and parts[1] in ANIMALS and name not in BANNED_WORDS
